# Generated by Django 2.2.16 on 2022-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221106_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Введите дату публикации поста',
                verbose_name='Дата публикации',
            ),
        ),
    ]
